pr2_fl_caster_test:
  type: pr2_mechanism_controllers/CasterController
  joints:
    caster: fl_caster_rotation_joint
    wheel_l: fl_caster_l_wheel_joint
    wheel_r: fl_caster_r_wheel_joint
  caster_pid:
    p: 8.0
    d: 0.0
    i: 0.0
    i_clamp: 4.0
    i_clamp_max: 4.0
    i_clamp_min: -4.0
  wheel_pid:
    p: 100.0
    d: 5.0
    i: 0.0
    i_clamp: 0.0
    i_clamp_max: 0.0
    i_clamp_min: -0.0
pr2_fr_caster_test:
  type: pr2_mechanism_controllers/CasterController
  joints:
    caster: fr_caster_rotation_joint
    wheel_l: fr_caster_l_wheel_joint
    wheel_r: fr_caster_r_wheel_joint
  caster_pid:
    p: 8.0
    d: 0.0
    i: 0.0
    i_clamp: 4.0
    i_clamp_max: 4.0
    i_clamp_min: -4.0
  wheel_pid:
    p: 100.0
    d: 5.0
    i: 0.0
    i_clamp: 0.0
    i_clamp_max: 0.0
    i_clamp_min: -0.0
pr2_bl_caster_test:
  type: pr2_mechanism_controllers/CasterController
  joints:
    caster: bl_caster_rotation_joint
    wheel_l: bl_caster_l_wheel_joint
    wheel_r: bl_caster_r_wheel_joint
  caster_pid:
    p: 8.0
    d: 0.0
    i: 0.0
    i_clamp: 4.0
    i_clamp_max: 4.0
    i_clamp_min: -4.0
  wheel_pid:
    p: 100.0
    d: 5.0
    i: 0.0
    i_clamp: 0.0
    i_clamp_max: 0.0
    i_clamp_min: -0.0
pr2_br_caster_test:
  type: pr2_mechanism_controllers/CasterController
  joints:
    caster: br_caster_rotation_joint
    wheel_l: br_caster_l_wheel_joint
    wheel_r: br_caster_r_wheel_joint
  caster_pid:
    p: 8.0
    d: 0.0
    i: 0.0
    i_clamp: 4.0
    i_clamp_max: 4.0
    i_clamp_min: -4.0
  wheel_pid:
    p: 100.0
    d: 5.0
    i: 0.0
    i_clamp: 0.0
    i_clamp_max: 0.0
    i_clamp_min: -0.0
